### ISSUE TITLE
db conn on server initiate

### ISSUE THREAD

**Issue by janjulius** [janjulius/Deklin#1]
at com.rs.utils.files.DatabaseUtils.openDatabase(DatabaseUtils.java:28)
	at com.rs.utils.files.DatabaseUtils.openServerDatabase(DatabaseUtils.java:16)
	at com.rs.game.spawning.ObjectSpawning.init(ObjectSpawning.java:26)
	at com.rs.Launcher.main(Launcher.java:52)

	at com.rs.utils.files.DatabaseUtils.openDatabase(DatabaseUtils.java:28)
	at com.rs.utils.files.DatabaseUtils.openServerDatabase(DatabaseUtils.java:16)
	at com.rs.game.spawning.NpcSpawning.init(NpcSpawning.java:27)
	at com.rs.Launcher.main(Launcher.java:53)

**Comment by gnos1337** [comment]
kanker
